# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I4bUJ-CcYUq0aIOqJhtCSMabRm4_-Fqm
"""

from scipy import stats

x= [151,174,138,186,128,136,179,163,152,165]

y= [63,81,56,91,47,57,76,72,62,69]

slope, intercept,r,p, std_err = stats.linregress(x,y)

def myfunc(x):
  return slope * x + intercept

berat_badan = myfunc(151)

print(berat_badan)























